services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
     - ${POSTGRES_PORT}:5432
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}_development
    container_name: ${WEB_CONTAINER_NAME}